<?php

define('ROUTE_LIST', [
    '/' => ['view' => 'front/home', 'title' => 'Accueil'],
    '/rubriques' => ['view' => 'front/rubriques', 'title' => 'Rubriques'],
    '/rubriques/actualite' => ['view' => 'front/rubrique', 'title' => 'Actualité', 'data' => ['rubrique' => 'Actualité']],
    '/rubriques/campus' => ['view' => 'front/rubrique', 'title' => 'Campus', 'data' => ['rubrique' => 'Campus']],
    '/rubriques/focus' => ['view' => 'front/rubrique', 'title' => 'Focus / Dossiers', 'data' => ['rubrique' => 'Focus / Dossiers']],
    '/rubriques/zoom' => ['view' => 'front/rubrique', 'title' => 'Zoom', 'data' => ['rubrique' => 'Zoom']],
    '/rubriques/reportages' => ['view' => 'front/rubrique', 'title' => 'Reportages', 'data' => ['rubrique' => 'Reportages']],
    '/rubriques/enquetes' => ['view' => 'front/rubrique', 'title' => 'Enquêtes', 'data' => ['rubrique' => 'Enquêtes']],
    '/rubriques/interviews' => ['view' => 'front/rubrique', 'title' => 'Interviews', 'data' => ['rubrique' => 'Interviews']],
    '/article' => ['view' => 'front/article', 'title' => 'Article'],
    '/boutique' => ['view' => 'front/boutique', 'title' => 'Boutique PDF'],
    '/boutique/numero' => ['view' => 'front/boutique-detail', 'title' => 'Détail PDF'],
    '/a-propos' => ['view' => 'front/about', 'title' => 'À propos'],
    '/contact' => ['view' => 'front/contact', 'title' => 'Contact'],
    '/recherche' => ['view' => 'front/search', 'title' => 'Recherche'],
    '/connexion' => ['view' => 'user/login', 'title' => 'Connexion'],
    '/inscription' => ['view' => 'user/register', 'title' => 'Inscription'],
    '/profil' => ['view' => 'user/profile', 'title' => 'Profil'],
    '/profil/achats' => ['view' => 'user/purchases', 'title' => 'Historique des achats'],
    '/profil/commentaires' => ['view' => 'user/comments', 'title' => 'Mes commentaires'],
    '/profil/mot-de-passe' => ['view' => 'user/password', 'title' => 'Mot de passe'],
    '/admin' => ['view' => 'admin/dashboard', 'title' => 'Tableau de bord'],
    '/admin/articles' => ['view' => 'admin/articles', 'title' => 'Articles'],
    '/admin/categories' => ['view' => 'admin/categories', 'title' => 'Rubriques'],
    '/admin/pages' => ['view' => 'admin/pages', 'title' => 'Pages'],
    '/admin/medias' => ['view' => 'admin/media', 'title' => 'Médiathèque'],
    '/admin/pdf' => ['view' => 'admin/pdf', 'title' => 'PDF'],
    '/admin/commandes' => ['view' => 'admin/orders', 'title' => 'Commandes'],
    '/admin/utilisateurs' => ['view' => 'admin/users', 'title' => 'Utilisateurs'],
    '/admin/commentaires' => ['view' => 'admin/comments', 'title' => 'Commentaires'],
    '/admin/stats' => ['view' => 'admin/stats', 'title' => 'Statistiques'],
]);
